#!/usr/bin/env node
/**
 * AI test-case generator (CLI).
 *
 *   npm run ai:generate -- --story "As a patient I want to cancel an appointment"
 *   npm run ai:generate -- --openapi ./openapi.json --name booking-api
 *
 * Produces DRAFT artefacts for human review in `generated/`:
 *   <name>.cases.md   - positive / negative / boundary cases in prose
 *   <name>.spec.ts    - a scaffolded spec with each case as a `test.fixme`
 *
 * Nothing is added to the running suite. Generated specs are marked `fixme` on
 * purpose: a generated test that has never been read by a human is a liability,
 * not coverage.
 */
import { askForJson, describeSkip } from '@ai/client';
import { aiConfig } from '@ai/config';
import { isRecord, truncate } from '@ai/parse';
import fs from 'fs';
import path from 'path';

const SYSTEM_PROMPT = `You are a senior SDET designing end-to-end test cases.

Given a user story or an OpenAPI specification, produce test cases in three groups:
- positive: the intended journeys that must work
- negative: invalid input, missing permissions, rejected states
- boundary: limits, empty and maximum values, edge dates, off-by-one conditions

Each case needs a short imperative title, the preconditions, the steps, and the
expected result. Be specific and verifiable - "the page looks right" is not an
expected result. Do not invent product behaviour the input does not imply; where
something is genuinely ambiguous, say so in the case's notes.`;

const SCHEMA: Record<string, unknown> = {
  type: 'object',
  properties: {
    feature: { type: 'string' },
    cases: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          type: { type: 'string', enum: ['positive', 'negative', 'boundary'] },
          preconditions: { type: 'string' },
          steps: { type: 'array', items: { type: 'string' } },
          expected: { type: 'string' },
          notes: { type: 'string' },
        },
        required: ['title', 'type', 'preconditions', 'steps', 'expected'],
        additionalProperties: false,
      },
    },
  },
  required: ['feature', 'cases'],
  additionalProperties: false,
};

interface GeneratedCase {
  title: string;
  type: 'positive' | 'negative' | 'boundary';
  preconditions: string;
  steps: string[];
  expected: string;
  notes?: string;
}

export function parseArgs(argv: string[]): Record<string, string> {
  const args: Record<string, string> = {};
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (token?.startsWith('--')) {
      const key = token.slice(2);
      const next = argv[i + 1];
      if (next && !next.startsWith('--')) {
        args[key] = next;
        i += 1;
      } else {
        args[key] = 'true';
      }
    }
  }
  return args;
}

/** Turns validated cases into a scaffolded, deliberately-skipped spec file. */
export function renderSpec(feature: string, cases: GeneratedCase[]): string {
  const body = cases
    .map((testCase) => {
      const steps = testCase.steps.map((step) => `    //   - ${step}`).join('\n');
      const tag = testCase.type === 'positive' ? '@smoke' : '@regression';
      return [
        `  // Preconditions: ${testCase.preconditions}`,
        `  // Steps:`,
        steps,
        `  // Expected: ${testCase.expected}`,
        testCase.notes ? `  // Notes: ${testCase.notes}` : '',
        `  test.fixme(${JSON.stringify(testCase.title)}, { tag: ['${tag}'] }, async ({ page }) => {`,
        `    // TODO: implement using page objects from src/pages, then remove .fixme`,
        `    void page;`,
        `  });`,
      ]
        .filter(Boolean)
        .join('\n');
    })
    .join('\n\n');

  return [
    `import { test } from '@fixtures/index';`,
    '',
    '/**',
    ` * DRAFT - generated by \`npm run ai:generate\`, not yet reviewed.`,
    ' *',
    ' * Every case is `test.fixme` so it cannot report a false pass. Implement the',
    ' * body against real page objects, then drop `.fixme`.',
    ' */',
    `test.describe(${JSON.stringify(feature)}, () => {`,
    body,
    '});',
    '',
  ].join('\n');
}

export function renderMarkdown(feature: string, cases: GeneratedCase[]): string {
  const groups: GeneratedCase['type'][] = ['positive', 'negative', 'boundary'];
  const sections = groups.map((group) => {
    const items = cases.filter((testCase) => testCase.type === group);
    if (items.length === 0) return '';
    const rows = items
      .map((testCase, index) =>
        [
          `### ${index + 1}. ${testCase.title}`,
          '',
          `**Preconditions:** ${testCase.preconditions}`,
          '',
          '**Steps:**',
          ...testCase.steps.map((step, i) => `${i + 1}. ${step}`),
          '',
          `**Expected:** ${testCase.expected}`,
          testCase.notes ? `\n**Notes:** ${testCase.notes}` : '',
        ].join('\n')
      )
      .join('\n\n');
    return `## ${group[0]?.toUpperCase()}${group.slice(1)}\n\n${rows}`;
  });

  return [
    `# ${feature} — draft test cases`,
    '',
    '> Generated by the AI layer for human review. Not executable coverage.',
    '',
    ...sections.filter(Boolean),
    '',
  ].join('\n');
}

function readInput(args: Record<string, string>): { label: string; content: string } | undefined {
  if (args['story']) {
    return { label: 'User story', content: args['story'] };
  }
  if (args['openapi']) {
    const specPath = path.resolve(process.cwd(), args['openapi']);
    if (!fs.existsSync(specPath)) {
      console.error(`OpenAPI spec not found: ${specPath}`);
      return undefined;
    }
    // Specs are large; the model only needs the shape, not every example.
    return {
      label: 'OpenAPI specification',
      content: truncate(fs.readFileSync(specPath, 'utf-8'), 40_000),
    };
  }
  return undefined;
}

async function main(): Promise<number> {
  const args = parseArgs(process.argv.slice(2));
  const input = readInput(args);

  if (!input) {
    console.error('Usage: npm run ai:generate -- --story "<user story>" [--name <slug>]');
    console.error('   or: npm run ai:generate -- --openapi <path> [--name <slug>]');
    return 1;
  }

  if (!aiConfig.enabled) {
    console.error(`Cannot generate: ${describeSkip(aiConfig.apiKey ? 'disabled' : 'no-api-key')}`);
    console.error('Set ANTHROPIC_API_KEY and AI_ENABLED=true.');
    return 1;
  }

  const response = await askForJson({
    system: SYSTEM_PROMPT,
    prompt: `${input.label}:\n\n${input.content}`,
    schema: SCHEMA,
    maxTokens: 16_000,
  });

  if (!response.ok) {
    console.error(`Generation failed: ${describeSkip(response.reason)}`);
    return 1;
  }

  const feature =
    typeof response.data['feature'] === 'string' ? response.data['feature'] : 'Generated feature';
  const rawCases = response.data['cases'];
  const cases = (Array.isArray(rawCases) ? rawCases : []).filter(
    isRecord
  ) as unknown as GeneratedCase[];

  if (cases.length === 0) {
    console.error('The model returned no test cases.');
    return 1;
  }

  const slug = (args['name'] ?? feature)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  const outDir = path.resolve(process.cwd(), 'generated');
  fs.mkdirSync(outDir, { recursive: true });

  const mdPath = path.join(outDir, `${slug}.cases.md`);
  const specPath = path.join(outDir, `${slug}.spec.ts`);
  fs.writeFileSync(mdPath, renderMarkdown(feature, cases), 'utf-8');
  fs.writeFileSync(specPath, renderSpec(feature, cases), 'utf-8');

  console.log(`Generated ${cases.length} draft case(s) for "${feature}":`);
  console.log(`  ${path.relative(process.cwd(), mdPath)}`);
  console.log(
    `  ${path.relative(process.cwd(), specPath)}  (all test.fixme - review before enabling)`
  );
  return 0;
}

if (require.main === module) {
  main()
    .then((code) => process.exit(code))
    .catch((error: unknown) => {
      console.error(error);
      process.exit(1);
    });
}
