import { askForJson } from '@ai/client';
import { isRecord, normaliseConfidence, readString, truncate } from '@ai/parse';
import {
  AiResult,
  FailureContext,
  TRIAGE_CATEGORIES,
  TriageCategory,
  TriageVerdict,
} from '@ai/types';

const SYSTEM_PROMPT = `You are a senior test automation engineer triaging a failed end-to-end test.

Classify the failure into exactly one category:
- product-bug: the application under test behaved incorrectly. The test is right.
- test-bug: the test or its locators/assumptions are wrong. The application is right.
- environment-issue: infrastructure, network, auth, test data or configuration - neither the product nor the test logic.
- flaky: a timing or ordering race; the same code would likely pass on a retry.

Judge only from the evidence given. Say so in your reasoning when the evidence is
thin rather than inventing a cause, and lower your confidence accordingly.
Keep reasoning to two sentences and suggestedAction to one concrete next step.`;

const TRIAGE_SCHEMA: Record<string, unknown> = {
  type: 'object',
  properties: {
    category: { type: 'string', enum: [...TRIAGE_CATEGORIES] },
    confidence: { type: 'number' },
    reasoning: { type: 'string' },
    suggestedAction: { type: 'string' },
  },
  required: ['category', 'confidence', 'reasoning', 'suggestedAction'],
  additionalProperties: false,
};

/** Builds the user prompt. Exported so unit tests can assert on redaction. */
export function buildTriagePrompt(context: FailureContext): string {
  const parts = [
    `Test: ${context.testTitle}`,
    `File: ${context.filePath}`,
    `Browser project: ${context.projectName}`,
    `Retry attempt: ${context.retryIndex}`,
    `Duration: ${context.durationMs}ms`,
    '',
    'Error:',
    truncate(context.errorMessage, 2_000),
  ];

  if (context.stack) parts.push('', 'Stack:', truncate(context.stack, 2_000));
  if (context.apiResponse) parts.push('', 'API response:', truncate(context.apiResponse, 2_000));
  if (context.domSnapshot) parts.push('', 'DOM at failure:', context.domSnapshot);

  return parts.join('\n');
}

/**
 * Validates a raw model response into a `TriageVerdict`.
 *
 * Separated from the network call so the fallback path is unit-testable: an
 * unknown category or a missing field must degrade, never throw.
 */
export function toTriageVerdict(data: unknown): AiResult<TriageVerdict> {
  if (!isRecord(data)) {
    return { ok: false, reason: 'invalid-shape', detail: 'not an object' };
  }

  const rawCategory = readString(data, 'category').toLowerCase();
  const category = TRIAGE_CATEGORIES.find((known) => known === rawCategory);
  if (!category) {
    return { ok: false, reason: 'invalid-shape', detail: `unknown category "${rawCategory}"` };
  }

  return {
    ok: true,
    data: {
      category: category as TriageCategory,
      confidence: normaliseConfidence(data['confidence']),
      reasoning: readString(data, 'reasoning', 'No reasoning supplied.'),
      suggestedAction: readString(data, 'suggestedAction', 'No suggested action supplied.'),
    },
  };
}

/** Classifies a failure. Returns a skip reason rather than throwing. */
export async function triageFailure(context: FailureContext): Promise<AiResult<TriageVerdict>> {
  const response = await askForJson({
    system: SYSTEM_PROMPT,
    prompt: buildTriagePrompt(context),
    schema: TRIAGE_SCHEMA,
  });

  if (!response.ok) return response;
  return toTriageVerdict(response.data);
}

/** Renders a verdict as markdown for attachment to the test report. */
export function renderVerdict(verdict: TriageVerdict): string {
  const icon: Record<TriageCategory, string> = {
    'product-bug': '🐞',
    'test-bug': '🧪',
    'environment-issue': '🌐',
    flaky: '🎲',
  };
  const pct = Math.round(verdict.confidence * 100);

  return [
    `## ${icon[verdict.category]} AI triage: ${verdict.category}`,
    '',
    `**Confidence:** ${pct}%`,
    '',
    `**Reasoning:** ${verdict.reasoning}`,
    '',
    `**Suggested action:** ${verdict.suggestedAction}`,
    '',
    '---',
    '_Advisory only. This classification is generated by an AI model and has no',
    'effect on the pass/fail result of this test._',
  ].join('\n');
}
