import { FlakyAnalysis, FlakyTestRecord } from '@ai/types';

/**
 * Pure flakiness aggregation - no AI, no I/O.
 *
 * Kept deterministic and dependency-free so the scoring is unit-testable and
 * so the analyzer still produces a useful report with the AI layer switched
 * off. AI only ever adds the "probable cause" prose on top.
 */

/** The subset of Playwright's JSON reporter output that we rely on. */
export interface PlaywrightJsonReport {
  suites?: JsonSuite[];
}

interface JsonSuite {
  title?: string;
  suites?: JsonSuite[];
  specs?: JsonSpec[];
}

interface JsonSpec {
  title?: string;
  tests?: JsonTest[];
}

interface JsonTest {
  results?: JsonResult[];
}

interface JsonResult {
  status?: string;
  error?: { message?: string };
}

export interface TestOutcome {
  title: string;
  passed: boolean;
  error?: string;
}

/** Walks the nested suite tree and flattens it into one outcome per spec. */
export function extractOutcomes(report: PlaywrightJsonReport): TestOutcome[] {
  const outcomes: TestOutcome[] = [];

  const walk = (suites: JsonSuite[] | undefined, trail: string[]): void => {
    for (const suite of suites ?? []) {
      const path = suite.title ? [...trail, suite.title] : trail;

      for (const spec of suite.specs ?? []) {
        const title = [...path, spec.title ?? '(untitled)'].join(' › ');

        for (const test of spec.tests ?? []) {
          // A spec's last attempt is its verdict; earlier retries are noise here.
          const attempts = test.results ?? [];
          const final = attempts[attempts.length - 1];
          if (!final) continue;

          outcomes.push({
            title,
            passed: final.status === 'passed',
            error: final.error?.message,
          });
        }
      }

      walk(suite.suites, path);
    }
  };

  walk(report.suites, []);
  return outcomes;
}

/**
 * Scores instability as `1 - |2 * failureRate - 1|`.
 *
 * Peaks at 1.0 for a 50/50 split and falls to 0 for a test that always passes
 * OR always fails. That matters: a consistently failing test is a broken test,
 * not a flaky one, and mixing the two buries the real flakes.
 */
export function flakinessScore(failures: number, runs: number): number {
  if (runs === 0) return 0;
  const failureRate = failures / runs;
  return Number((1 - Math.abs(2 * failureRate - 1)).toFixed(3));
}

/** Aggregates several runs into a ranked flakiness report. */
export function analyzeRuns(reports: PlaywrightJsonReport[]): FlakyAnalysis {
  const byTitle = new Map<string, { runs: number; failures: number; errors: string[] }>();

  for (const report of reports) {
    for (const outcome of extractOutcomes(report)) {
      const entry = byTitle.get(outcome.title) ?? { runs: 0, failures: 0, errors: [] };
      entry.runs += 1;
      if (!outcome.passed) {
        entry.failures += 1;
        if (outcome.error && entry.errors.length < 3) entry.errors.push(outcome.error);
      }
      byTitle.set(outcome.title, entry);
    }
  }

  const flaky: FlakyTestRecord[] = [];
  for (const [title, entry] of byTitle) {
    // Both extremes are stable outcomes - only mixed results are flaky.
    if (entry.failures === 0 || entry.failures === entry.runs) continue;

    flaky.push({
      title,
      runs: entry.runs,
      failures: entry.failures,
      failureRate: Number((entry.failures / entry.runs).toFixed(3)),
      flakinessScore: flakinessScore(entry.failures, entry.runs),
      errorSamples: entry.errors,
    });
  }

  flaky.sort((a, b) => b.flakinessScore - a.flakinessScore || b.failures - a.failures);

  return { totalRuns: reports.length, flaky };
}

/** Renders the analysis as a markdown report. */
export function renderFlakyReport(analysis: FlakyAnalysis): string {
  if (analysis.flaky.length === 0) {
    return [
      '# Flakiness report',
      '',
      `Analysed ${analysis.totalRuns} run(s). **No flaky tests detected** — every test`,
      'either passed consistently or failed consistently.',
      '',
    ].join('\n');
  }

  const rows = analysis.flaky
    .map(
      (record) =>
        `| ${record.title} | ${record.failures}/${record.runs} | ${(record.failureRate * 100).toFixed(0)}% | ${record.flakinessScore} |`
    )
    .join('\n');

  const causes = analysis.probableCauses
    ? [
        '',
        '## Probable causes (AI-assisted)',
        '',
        ...Object.entries(analysis.probableCauses).map(
          ([title, cause]) => `**${title}**\n\n${cause}\n`
        ),
        '_Advisory only — generated by an AI model from error samples._',
      ]
    : ['', '_Run with `AI_ENABLED=true` to add probable-cause analysis._'];

  return [
    '# Flakiness report',
    '',
    `Analysed **${analysis.totalRuns}** run(s); found **${analysis.flaky.length}** flaky test(s).`,
    '',
    'Score peaks at 1.0 for a 50/50 pass–fail split. Consistently failing tests are',
    'excluded — those are broken, not flaky.',
    '',
    '| Test | Failures | Failure rate | Flakiness |',
    '| --- | --- | --- | --- |',
    rows,
    ...causes,
    '',
  ].join('\n');
}
